services:
  db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: ${INSTALL_DEV:-false}
    image: "${DOCKER_IMAGE_BACKEND:-my_default_backend_image}:${TAG:-latest}"
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY_USER=${SECRET_KEY_USER?Variable not set}
      - SECRET_KEY_DEVICE=${SECRET_KEY_DEVICE?Variable not set}
      - DB_URL=${DB_URL}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: "${DOCKER_IMAGE_FRONTEND:-my_default_frontend_image}:${TAG:-latest}"
    container_name: frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:80"

volumes:
  mongo-data:
